[project]
name = "fast-font-tools"
version = "0.1.0"
description = "Tools for creating Fast fonts from regular and bold font pairs"
requires-python = ">=3.13"
dependencies = [
    "fonttools>=4.59.2",
]
